sugarcube-2:
  macros:
    Dialogue:
      name: Dialogue
      container: true
      parameters:
        - "'player' &+ 'You'"
        - "'youngPlayer' &+ 'Young you'"
        - "'Tasha' &+ 'Tasha'"
        - "'Simon' &+ 'Simon'"
        - "'Kris'|'KrisCasualObsessed'|'KrisCasual'|'KrisObsessed' &+ 'Kris'"
        - "'Johan'|'JohanFancy' &+ 'Johan'|'JO-HAN, The Magnificent'"
        - "'Elena'|'ElenaHappy' &+ 'Elena'"
        - "'Emma'|'EmmaFitness' &+ 'Emma'|'Office lady'|'Businesswoman'"
        - "'Nathan' &+ 'Nathan'"
        - "'youngNat' &+ 'Nathan'"
        - "'Natalie' &+ 'Natalie'"
        - "'toshiUnknown' &+ 'Toshi'"
        - "'Eddy' &+ 'Eddy'"
        - "'randomPerson'|'johanFriend1'|'johanFriend2' &+ string"
        - "'???' &+ '???'"
        - "'quest' &+ '_line'|'New Goal'"
    PersonalityCheck:
      name: PersonalityCheck
      container: true
      parameters:
        - bareword &+
          ('<'|'>'|'<='|'>='|'=='|'==='|'eq'|'is'|'transition'|'t8n') &+ number
          &+ string
    addQuest:
      name: addQuest
      parameters:
        - string
    gameLink:
      name: gameLink
      container: true
      parameters:
        - string &+ string &+ (...bareword|string)
    addBreastsSlow:
      name: addBreastsSlow
      parameters:
        - number
    addQuestProgress:
      name: addQuestProgress
      parameters:
        - string &+ number
    addTrigger:
      name: addTrigger
      parameters:
        - string &+ bool &+ bool
        - string
    addMinutes:
      name: addMinutes
      parameters:
        - number
    addToLog:
      name: addToLog
      parameters:
        - string
    update:
      name: update
      parameters:
        - ""
    clothingFitDescription:
      name: clothingFitDescription
      parameters:
        - ""
        - string
    ClothingStoreWidget:
      name: ClothingStoreWidget
      parameters:
        - var
    skillIncrease:
      name: skillIncrease
      parameters:
        - "'gaming'|'Working out'|'Book keeping'|'Sewing'|'Cooking' &+ number"
    Failed:
      name: Failed
      parameters:
        - ""
    addHeightSlow:
      name: addHeightSlow
      parameters:
        - number
    addMuscleSlow:
      name: addMuscleSlow
      parameters:
        - number
    heighNumeral:
      name: heighNumeral
      parameters:
        - ""
    live:
      name: live
      parameters:
        - ...text
    addFatSlow:
      name: addFatSlow
      parameters:
        - number
    personalityIncrease:
      name: personalityIncrease
      parameters:
        - string &+ number
    BreastSizeDescription:
      name: BreastSizeDescription
      parameters:
        - ""
    breastCupDescriptors:
      name: breastCupDescriptors
      parameters:
        - ""
    BreastsWeightDescription:
      name: BreastsWeightDescription
      parameters:
        - ""
    cleaning:
      name: cleaning
      parameters:
        - string
    workoutLink:
      name: workoutLink
      parameters:
        - " 'home'|'gym' "
    getMeasurement:
      name: getMeasurement
      parameters:
        - "
          'thigh'|'calve'|'chest'|'waist'|'hips'|'neck'|'upperArm'|'lowerArm'|'\
          wrist'|'knee'|'ankle'|'weight' |+ bool "
    numeralConversion:
      name: numeralConversion
      parameters:
        - number |+ bool
    fullBody:
      name: fullBody
      parameters:
        - ""
    bodyDescription:
      name: bodyDescription
      parameters:
        - ""
    ClothingFitCalculator:
      name: ClothingFitCalculator
      parameters:
        - bool
    setPlayerSizeNeeded:
      name: setPlayerSizeNeeded
      parameters:
        - ""
    DayUpdate:
      name: DayUpdate
      parameters:
        - ""
    BodyTypeDescription:
      name: BodyTypeDescription
      parameters:
        - ""
    bodyHairDescription:
      name: bodyHairDescription
      parameters:
        - ""
    heightDescription:
      name: heightDescription
      parameters:
        - ""
    headDescription:
      name: headDescription
      parameters:
        - ""
    upperBodyDescription:
      name: upperBodyDescription
      parameters:
        - ""
    lowerBodyDescription:
      name: lowerBodyDescription
      parameters:
        - ""
    lipsDescription:
      name: lipsDescription
      parameters:
        - ""
    tongueDescription:
      name: tongueDescription
      parameters:
        - ""
    limitedNumberbox:
      name: limitedNumberbox
      parameters:
        - string &+ number &+ number &+ number
    liveblock:
      name: liveblock
      container: true
      parameters:
        - ""
    BreastsDescription:
      name: BreastsDescription
      parameters:
        - ""
    hipDescription:
      name: hipDescription
      parameters:
        - ""
    assDescription:
      name: assDescription
      parameters:
        - ""
    legLenghtDescription:
      name: legLenghtDescription
      parameters:
        - ""
    dickDescription:
      name: dickDescription
      parameters:
        - ""
    radarChart:
      name: radarChart
      parameters:
        - ""
    streamingViewerIncomeCalc:
      name: streamingViewerIncomeCalc
      parameters:
        - " 'gaming'|'talking' "
    dialogPicker:
      name: dialogPicker
      parameters:
        - " 'Johan'|'Emma'|'Elena'|'ElenaShy'|'KrisObsessed'|'PostSleep'|'Kris' "
    updateNPCLastSeen:
      name: updateNPCLastSeen
      parameters:
        - string
    addTriggerInternal:
      name: addTriggerInternal
      container: true
      parameters:
        - string &+ bool &+ bool
    sizeCalc:
      name: sizeCalc
      parameters:
        - number &+ number &+ number &+ '$weight'|'$chestSize'|'$waistSize'|'$hipsSize'|'$neckSize'|'$upperArmSize'|'$lowerArmSize'|'$wristSize'|'$thighsSize'|'$kneeSize'|'$calveSize'|'$ankleSize'
    weightConversion:
      name: weightConversion
      parameters:
        - number
    clothingSize:
      name: clothingSize
      parameters:
        - number
    addDickSlow:
      name: addDickSlow
      parameters:
        - number
    sleepUpdate:
      name: sleepUpdate
      parameters:
        - ""
    dailyConsumables:
      name: dailyConsumables
      parameters:
        - ""
    clothingCraftingWidget:
      name: clothingCraftingWidget
      parameters:
        - ""
    skillCheck:
      name: skillCheck
      parameters:
        - " 'Sewing' &+ number "
    changeClothing:
      name: changeClothing
      parameters:
        - " 'top'|'bra'|'bottom'|'overwear'|'underwear' "
    TailorWidget:
      name: TailorWidget
      parameters:
        - ""
    sewingProjectsWidget:
      name: sewingProjectsWidget
      parameters:
        - ""
    sewingTailoringWidget:
      name: sewingTailoringWidget
      parameters:
        - ""
    postSleepDietDescription:
      name: postSleepDietDescription
      parameters:
        - ""
    krisGift:
      name: krisGift
      parameters:
        - " 'potion' "
    addMotivation:
      name: addMotivation
      parameters:
        - number
    addMinimumExhaustion:
      name: addMinimumExhaustion
      parameters:
        - number
    ConsumablePopup:
      name: ConsumablePopup
      parameters:
        - number
    removeTrigger:
      name: removeTrigger
      parameters:
        - string &+ string
    outfitDescription:
      name: outfitDescription
    rivalName:
      name: rivalName
    RivalI:
      name: RivalI
    RivalI:
      name: RivalI
    rivalMy:
      name: rivalMy
    rivalMe:
      name: rivalMe
    rivalMine:
      name: rivalMine
    playNatEvent:
      name: playNatEvent
      parameters:
        - string
    LabWidget:
      name: LabWidget
      parameters:
        - bool